name: Deploy

on:
  workflow_run:
    workflows: ["Build & Push Docker Image"]
    types: [completed]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.event.repository.full_name }}

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v6

      - name: Deploy container
        run: |
          export DOCKER_GID=$(getent group docker | cut -d: -f3)
          cp ~/agent-box-runner/.env .
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker compose up -d
